name: macos

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macos-10.15 }
        - { os: macos-11.0  }
        build: [Debug, Release]

    name: "${{matrix.config.os}}:${{matrix.build}}"
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build}}

    - name: Build
      run: cmake --build . --config ${{matrix.build}}

    - name: Tests
      run: ctest --output-on-failure -C ${{matrix.build}}
